name: Build site
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish to retype branch

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      #- name: Clean existing retype branch
        #run: |
          #git push -d origin retype

      - name: Symlink stuff for redirecton
        run: |
          _links=(
              "gearlock/user-guide/getting-geardump.md|common-issues/gathering-logs.md"
          )

          exit 0; # Temporarily disable this

          for _link in "${_links[@]}"; do {
              _caller="${_link%%|*}";
              _target="${_link##*|}";

              ln -srf "$_target" "$_caller";

              unset _caller _target;
          } done


      - uses: retypeapp/action-build@v1

      - uses: retypeapp/action-github-pages@v1
        with:
          update-branch: true
